# Generated by Django 2.1.5 on 2021-08-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_offer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
    ]
